project:
  type: book
  output-dir: docs
  resources: 
    - .nojekyll

book:
  title: "USACE Recreation Ontology Review"
  author: "EGIS Modernization"
  sidebar:
    style: docked
    search: true
  chapters:
    - index.qmd
    - intro.qmd
    - ontology-overview.qmd
    - rec-vis.qmd
    - 07-recreation-spatial-diagrams.qmd
    - 12-recreation-sdsfie-crosswalk.qmd

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true

execute:
  warning: false
  message: false