project:
  type: book
  output-dir: docs
  resources: 
    - .nojekyll

book:
  title: "USACE Recreation Ontology Review"
  author: "EGIS Modernization"
  sidebar:
    style: docked
    search: true
  chapters:
    - index.qmd
    - ontology-overview.qmd
    - 03-recreation-diagrams.qmd
    - 07-recreation-spatial-diagrams.qmd
    - 10-recreation-modernization-decision-log.qmd
    - 12-recreation-sdsfie-crosswalk.qmd
    - rec-ontology.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  warning: false
  message: false